name: Deploy to Server

on:
  push:
    branches:
      - main

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 35.159.223.170
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            # Update the script based on the identified issue
            # For example, if the public key is missing:
            #   sudo ssh-copy-id -i ~/.ssh/id_rsa ${{ env.SERVER_USERNAME }}@${{ env.SERVER_IP }}
            # Or if the SSH configuration is incorrect:
            #   sudo systemctl restart sshd
