name: Build, Push and Deploy Docker Image

on:
  push:
    branches: [ "unknown17" ]
  pull_request:
    branches: [ "unknown17" ]

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 3.127.221.197
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "go1/src" ]; then
              mkdir -p go1/src
            fi
            
            if [ ! -d "go1/src/internship" ]; then
              git clone https://github.com/unknownn17/Internship_Task.git  go1/src/internship
            fi
            
            cd go1/src/internship
            
            sudo docker compose down
            sudo docker compose up --build -d
          script_stop: true
          timeout: 200s
